@baseUrl = http://127.0.0.1:3000
@apiUrl = http://127.0.0.1:3000/api
# ekat http-testit

### get juuri
GET {{baseUrl}}
### get juuri /
GET {{baseUrl}}/

### POST Moro, jsonia bodyssa
POST {{baseUrl}}/api/moro
content-type: application/json

{
    "sender": "OJ",
    "message": "testitervehdys"
}

## Items

### GET all items
GET {{apiUrl}}/items

### GET item by id
GET {{apiUrl}}/items/3

### POST new item
POST {{apiUrl}}/items
Content-Type: application/json

{
  "name": "Sitruuna",
  "jotain": "jotain muuta"
}

### PUT update an item
PUT {{apiUrl}}/items/2
Content-Type: application/json

{
    "name": "PUT item2"
}

### DELETE item by id
DELETE {{apiUrl}}/items/3

## users

### GET all users
GET {{apiUrl}}/users

### GET user by id
GET {{apiUrl}}/users/3

### POST add new user
POST {{apiUrl}}/users
Content-Type: application/json

{
    "username": "johndoe5",
    "password": "password5",
    "email": "johndoe5@example.com"
}

### PUT update an user by id
PUT {{apiUrl}}/users/1
Content-Type: application/json

{
    "email": "newmail-johndoe@example.com"
}

### DELETE user by id
DELETE {{apiUrl}}/users/2

## login

### POST mock login
POST {{apiUrl}}/login
Content-Type: application/json

{
    "username": "johndoe5",
    "password": "password5"
}

### POST tehtavat. Json-body.
POST {{baseUrl}}/api/tehtavat
Content-Type: application/json

[{
    "id": "1",
    "tehtava": "Tee backend-tehtävä viikolta 1"
},
{
    "id": "2",
    "tehtava": "Tee backend-tehtävä viikolta 2"
}]

### PUT tehtavat :id. JSON-body.
PUT {{baseUrl}}/api/tehtavat/11
Content-Type: application/json

{
    "tehtava": "Tee backend-tehtävät viikolta 11"
}

### DELETE tehtavat :id
DELETE {{baseUrl}}/api/tehtavat/11

### GET olematon reitti/resurssi
GET {{baseUrl}}/egnlk
