@baseUrl = http://127.0.0.1:3000
@apiUrl = http://127.0.0.1:3000/api
# ekat http-testit

### get juuri
GET {{baseUrl}}
### get juuri /
GET {{baseUrl}}/

### POST Moro, jsonia bodyssa
POST {{baseUrl}}/api/moro
content-type: application/json

{
    "sender": "OJ",
    "message": "testitervehdys"
}

## Items

### GET all items
GET {{apiUrl}}/items

### GET item by id
GET {{apiUrl}}/items/3

### POST new item
POST {{apiUrl}}/items
Content-Type: application/json

{
  "name": "Sitruuna",
  "jotain": "jotain muuta"
}

### DELETE item by id
DELETE {{apiUrl}}/items/3

### POST tehtavat. Json-body.
POST {{baseUrl}}/api/tehtavat
Content-Type: application/json

[{
    "id": "1",
    "tehtava": "Tee backend-tehtävä viikolta 1"
},
{
    "id": "2",
    "tehtava": "Tee backend-tehtävä viikolta 2"
}]

### PUT tehtavat :id. JSON-body.
PUT {{baseUrl}}/api/tehtavat/11
Content-Type: application/json

{
    "tehtava": "Tee backend-tehtävät viikolta 11"
}

### DELETE tehtavat :id
DELETE {{baseUrl}}/api/tehtavat/11

### GET olematon reitti/resurssi
GET {{baseUrl}}/egnlk
