# ekat http-testit

### get juuri
GET http://localhost:3000

### POST Moro, jsonia bodyssa
POST http://127.0.0.1:3000/api/moro
content-type: application/json

{
    "sender": "OJ",
    "message": "testitervehdys"
}
