@baseUrl = http://127.0.0.1:3000
# ekat http-testit

### get juuri
GET {{baseUrl}}

### POST Moro, jsonia bodyssa
POST {{baseUrl}}/api/moro
content-type: application/json

{
    "sender": "OJ",
    "message": "testitervehdys"
}

### POST tehtavat. Json-body.
POST {{baseUrl}}/api/tehtavat
Content-Type: application/json

[{
    "id": "1",
    "tehtava": "Tee backend-tehtävä viikolta 1"
},
{
    "id": "2",
    "tehtava": "Tee backend-tehtävä viikolta 2"
}]

### PUT tehtavat :id. JSON-body.
PUT {{baseUrl}}/api/tehtavat/11
Content-Type: application/json

{
    "tehtava": "Tee backend-tehtävät viikolta 11"
}

### DELETE tehtavat :id
DELETE {{baseUrl}}/api/tehtavat/11

### GET olematon reitti/resurssi
GET {{baseUrl}}/egnlk
