@baseUrl = http://127.0.0.1:3000
@apiUrl = http://127.0.0.1:3000/api
# ekat http-testit

### get juuri
GET {{baseUrl}}
### get juuri /
GET {{baseUrl}}/

### POST Moro, jsonia bodyssa
POST {{baseUrl}}/api/moro
content-type: application/json

{
    "sender": "OJ",
    "message": "testitervehdys"
}

## Items

### GET all items
GET {{apiUrl}}/items

### GET item by id
GET {{apiUrl}}/items/3

### POST new item
POST {{apiUrl}}/items
Content-Type: application/json

{
  "name": "Sitruuna",
  "jotain": "jotain muuta"
}
